program: "train.py"
name: "DA6401_Assignment1_sweep"
method: "random"
metric:
  goal: maximize
  name: validation_accuracy
parameters:
  epochs:
    values: [5]
  batch_size:
    values: [64]
  num_layers:
    values: [5]
  hidden_size:
    values: [64,128]
  weight_decay:
    values: [0.0005]
  learning_rate: 
    max: 0.001
    min: 0.0001
    distribution: log_uniform_values
  optimizer: 
    values: ["adam"]
  weight_init: 
    values: ["xavier"]
  activation:
    values: ["tanh","relu","sigmoid"]
  loss:
    values: ["cross_entropy"]
